---
title: "2_transformations"
author: "Jennifer Neumaier"
date: "2/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Transformation

Loading Source files
```{r}
source("./src/3_get_imputed_data.R")
source("./src/2_convenience.R")
```

Loading Libraries
```{r}
library("tidyverse")
library ("devtools")

# https://cran.r-project.org/web/packages/easyCODA/easyCODA.pdf
library("easyCODA")
library("selbal")

# https://cran.r-project.org/web/packages/codacore/codacore.pdf
library("codacore")

```

TSS
Normalize patient-wise to the range of 0-1. -> find function for comparison
```{r}
# PCOS
PCOS_10_pc_TSS <- PCOS_abundances_10_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(PCOS_10_pc_TSS,"./data/transformed/PCOS_10_pc_TSS.txt", row.names = FALSE)

PCOS_50_pc_TSS <- PCOS_abundances_50_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(PCOS_50_pc_TSS,"./data/transformed/PCOS_50_pc_TSS.txt", row.names = FALSE)

# CRC
CRC_10_pc_TSS <- CRC_abundances_10_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(CRC_10_pc_TSS,"./data/transformed/CRC_10_pc_TSS.txt", row.names = FALSE)

CRC_50_pc_TSS <- CRC_abundances_50_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(CRC_50_pc_TSS,"./data/transformed/CRC_50_pc_TSS.txt", row.names = FALSE)

# EstMB
EstMB_10_pc_TSS <- EstMB_abundances_10_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(EstMB_10_pc_TSS,"./data/transformed/EstMB_10_pc_TSS.txt", row.names = FALSE)

EstMB_50_pc_TSS <- EstMB_abundances_50_pc %>%
  mutate_if(is.numeric, function(x) TSS(x))
write.table(EstMB_50_pc_TSS,"./data/transformed/EstMB_50_pc_TSS.txt", row.names = FALSE)
```


CLR
Normalize patient-wise to the geometric mean of each row.
What to do with LR.wt?
```{r}
# PCOS
PCOS_10_pc_CLR <- my_CLR(PCOS_abundances_10_pc)
write.table(PCOS_10_pc_CLR,"./data/transformed/PCOS_10_pc_CLR.txt", row.names = FALSE)

PCOS_50_pc_CLR <- my_CLR(PCOS_abundances_50_pc)
write.table(PCOS_50_pc_CLR,"./data/transformed/PCOS_50_pc_CLR.txt", row.names = FALSE)

# CRC
CRC_10_pc_CLR <- my_CLR(CRC_abundances_10_pc)
write.table(CRC_10_pc_CLR,"./data/transformed/CRC_10_pc_CLR.txt", row.names = FALSE)

CRC_50_pc_CLR <- my_CLR(CRC_abundances_50_pc)
write.table(CRC_50_pc_CLR,"./data/transformed/CRC_50_pc_CLR.txt", row.names = FALSE)

# EstMB
EstMB_10_pc_CLR <- my_CLR(EstMB_abundances_10_pc)
write.table(EstMB_10_pc_CLR,"./data/transformed/EstMB_10_pc_CLR.txt", row.names = FALSE)

EstMB_50_pc_CLR <- my_CLR(EstMB_abundances_50_pc)
write.table(EstMB_50_pc_CLR,"./data/transformed/EstMB_50_pc_CLR.txt", row.names = FALSE)
```

ALR
Later on: also change column names
What to do with LR.wt, part.wt, etc.?
```{r}
# PCOS ALR random
PCOS_10_pc_ALR_random <- my_random_ALR(PCOS_abundances_10_pc)
write.table(PCOS_10_pc_ALR_random,"./data/transformed/PCOS_10_pc_ALR_random.txt", row.names = FALSE)

PCOS_50_pc_ALR_random <- my_random_ALR(PCOS_abundances_50_pc)
write.table(PCOS_50_pc_ALR_random,"./data/transformed/PCOS_50_pc_ALR_random.txt", row.names = FALSE)

# CRC ALR random
CRC_10_pc_ALR_random <- my_random_ALR(CRC_abundances_10_pc)
write.table(CRC_10_pc_ALR_random,"./data/transformed/CRC_10_pc_ALR_random.txt", row.names = FALSE)

CRC_50_pc_ALR_random <- my_random_ALR(CRC_abundances_50_pc)
write.table(CRC_50_pc_ALR_random,"./data/transformed/CRC_50_pc_ALR_random.txt", row.names = FALSE)

# EstMB ALR random
EstMB_10_pc_ALR_random <- my_random_ALR(EstMB_abundances_10_pc)
write.table(EstMB_10_pc_ALR_random,"./data/transformed/EstMB_10_pc_ALR_random.txt", row.names = FALSE)

EstMB_50_pc_ALR_random <- my_random_ALR(EstMB_abundances_50_pc)
write.table(EstMB_50_pc_ALR_random,"./data/transformed/EstMB_50_pc_ALR_random.txt", row.names = FALSE)
```

Optimal ALR
```{r}
# PCOS ALR optimal
PCOS_10_pc_ALR_optimal <- my_optimal_ALR(PCOS_abundances_10_pc)
write.table(PCOS_10_pc_ALR_optimal,"./data/transformed/PCOS_10_pc_ALR_optimal.txt", row.names = FALSE)

PCOS_50_pc_ALR_optimal <- my_optimal_ALR(PCOS_abundances_50_pc)
write.table(PCOS_50_pc_ALR_optimal,"./data/transformed/PCOS_50_pc_ALR_optimal.txt", row.names = FALSE)

# CRC ALR optimal
CRC_10_pc_ALR_optimal <- my_optimal_ALR(CRC_abundances_10_pc)
write.table(CRC_10_pc_ALR_optimal,"./data/transformed/CRC_10_pc_ALR_optimal.txt", row.names = FALSE)

CRC_50_pc_ALR_optimal <- my_optimal_ALR(CRC_abundances_50_pc)
write.table(CRC_50_pc_ALR_optimal,"./data/transformed/CRC_50_pc_ALR_optimal.txt", row.names = FALSE)

# EstMB ALR optimal
EstMB_10_pc_ALR_optimal <- my_optimal_ALR(EstMB_abundances_10_pc)
write.table(EstMB_10_pc_ALR_optimal,"./data/transformed/EstMB_10_pc_ALR_optimal.txt", row.names = FALSE)

EstMB_50_pc_ALR_optimal <- my_optimal_ALR(EstMB_abundances_50_pc)
write.table(EstMB_50_pc_ALR_optimal,"./data/transformed/EstMB_50_pc_ALR_optimal.txt", row.names = FALSE)
```

Worst ALR
```{r}
# PCOS ALR worst
PCOS_10_pc_ALR_worst <- my_worst_ALR(PCOS_abundances_10_pc)
write.table(PCOS_10_pc_ALR_worst,"./data/transformed/PCOS_10_pc_ALR_worst.txt", row.names = FALSE)

PCOS_50_pc_ALR_worst <- my_worst_ALR(PCOS_abundances_50_pc)
write.table(PCOS_50_pc_ALR_worst ,"./data/transformed/PCOS_50_pc_ALR_worst.txt", row.names = FALSE)

# CRC ALR worst
CRC_10_pc_ALR_worst <- my_worst_ALR(CRC_abundances_10_pc)
write.table(CRC_10_pc_ALR_worst,"./data/transformed/CRC_10_pc_ALR_worst.txt", row.names = FALSE)

CRC_50_pc_ALR_worst <- my_worst_ALR(CRC_abundances_50_pc)
write.table(CRC_50_pc_ALR_worst,"./data/transformed/CRC_50_pc_ALR_worst.txt", row.names = FALSE)

# EstMB ALR worst
EstMB_10_pc_ALR_worst <- my_worst_ALR(EstMB_abundances_10_pc)
write.table(EstMB_10_pc_ALR_worst,"./data/transformed/EstMB_10_pc_ALR_worst.txt", row.names = FALSE)

EstMB_50_pc_ALR_worst <- my_worst_ALR(EstMB_abundances_50_pc)
write.table(EstMB_50_pc_ALR_worst,"./data/transformed/EstMB_50_pc_ALR_worst.txt", row.names = FALSE)
```

